-- Nuevos inserts para la tabla marcas
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Isolab', 'Alemania', FALSE, '/img/6e94eea0c1e9a710159baccea3949d701e18846b94bd501de2c61903d17a4b6e.webp', 'El gigante Aleman con un vasto catalogo' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Isolab');
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Trasons', 'India', FALSE, '/img/0d5a26c49a6d25b5d4a08fa14b917e2fd0c2f603e6a74d8c86c73e6ad3d2acd3.webp', 'La mejor marca de plásticos de la India' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Trasons');
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Biobase', 'China', FALSE, '/img/12a0bebb6a4fee590afe519d934358c755565a88ffd1c187fc56d1e8d8d1bba5.webp', 'La mejor marca de China para equipo medico' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Biobase');
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Radwag', 'Perú', FALSE, '/img/f9809b1426c3252f591c7495a9412684176ea4c2c4544c24343d75154bef7dc4.webp', 'El mayor fabricante de balanzas' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Radwag');
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Merck miliopore', 'Perú', FALSE, '/img/55289f6ff5a9fcf7535fcfb2e97f8612923fee7098b05524288a72059f701b59.webp', 'El mayor fabricante de reactivos en Latam' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Merck miliopore');
INSERT INTO marcas (nombre_marca, procedencia, anulado, link_imaguen, descripcion) SELECT 'Himedila laboritories', 'India', FALSE, '/img/00debfd0836f5500f696d83e4335dabec30389f0e6d638ab9cafb8884e31d80c.webp', 'Fabricante de la India' WHERE NOT EXISTS (SELECT 1 FROM marcas WHERE nombre_marca = 'Himedila laboritories');

-- Nuevos inserts para la tabla productos
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Rack para crioviales', 'Rack para crioviales.', 32.00, 2, '/img/rack.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Rack para crioviales');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Tubo de ensayo', 'Tubo de ensayo.', 2.50, 2, '/img/tubo.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Tubo de ensayo');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Agar Mac conkey', 'Agar Mac conkey.', 250.00, 5, '/img/macconkey-agar.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Agar Mac conkey');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Tamiz de 5 pulgadas', 'Tamiz de 5 pulgadas.', 120.00, 1, '/img/tamiz-de-laboratorio.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Tamiz de 5 pulgadas');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Escurridor de Laboratorio', 'Escurridor de Laboratorio.', 450.00, 1, '/img/escurridor-de-laboratorio.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Escurridor de Laboratorio');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Carboy de 20 LT', 'Carboy de 20 LT.', 350.00, 2, '/img/carboy-de-laboratorio.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Carboy de 20 LT');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Matraz de vidrio de 500 ml', 'Matraz de vidrio de 500 ml.', 22.00, 2, '/img/matraz-de-vidrio.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Matraz de vidrio de 500 ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Embudo de vidrio de 100mm', 'Embudo de vidrio de 100mm.', 32.00, 2, '/img/embudo-de-vidrio.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Embudo de vidrio de 100mm');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Rack para microtubos de 1.5ml', 'Rack para microtubos de 1.5ml.', 25.00, 2, '/img/rack-microtubos.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Rack para microtubos de 1.5ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Tubos de Microcentrifuga 1.5ml', 'Tubos de Microcentrifuga 1.5ml.', 69.00, 2, '/img/tubos-criogenicos.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Tubos de Microcentrifuga 1.5ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Pera de decantación de 100ml', 'Pera de decantación de 100ml.', 200.00, 2, '/img/pera-decantacion.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Pera de decantación de 100ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Frasco de vidrio de 100ml', 'Frasco de vidrio de 100ml.', 18.00, 2, '/img/frasco-vidrio.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Frasco de vidrio de 100ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Frasco de vidrio ambar 100ml', 'Frasco de vidrio ambar 100ml.', 25.00, 2, '/img/frasco-ambar.jpg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Frasco de vidrio ambar 100ml');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Agitador Magnetico + Calentador LCD de 20L', 'Agitador Magnetico + Calentador LCD de 20L.', 2590.00, 3, '/img/estufa_agitador.jpeg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Agitador Magnetico + Calentador LCD de 20L');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Microscopios Binocular LED', 'Microscopios Binocular LED.', 3400.00, 3, '/img/microscopi_binocular.jpeg' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Microscopios Binocular LED');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Refrigeradora de 2A -8C', 'Refrigeradora de 2A -8C.', 5500.00, 3, '/img/regfrigerador.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Refrigeradora de 2A -8C');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Centrifuga Clinica Multiuso con Rotor para Tubos', 'Centrifuga Clinica Multiuso con Rotor para Tubos.', 9400.00, 3, '/img/centrifuga.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Centrifuga Clinica Multiuso con Rotor para Tubos');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Cabina de Bioseguridad Clase 2', 'Cabina de Bioseguridad Clase 2.', 23500.00, 3, '/img/Cabina bioseguridad.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Cabina de Bioseguridad Clase 2');
INSERT INTO productos (nombre_producto, descripcion, precio, id_marca, link_imaguen) SELECT 'Balanza Analitica de 220 gr', 'Balanza Analitica de 220 gr.', 7390.00, 4, '/img/BALANZA-ANALITICA-DE-220.png' WHERE NOT EXISTS (SELECT 1 FROM productos WHERE nombre_producto = 'Balanza Analitica de 220 gr');

-- Nuevos inserts para usuario test
INSERT INTO users (username, password, superuser, email, ruc_dni_cliente, telefono, direccion_fiscal, anulado)
SELECT 'root', 'rootpass', TRUE, 'admin@email.com', '00000000', '000000000', 'Avenida Principal n°456', FALSE
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'root');
